/** 由于此文件会被cp到publish中，不能使用别名 */
import genaration from '../utils/classnames'

// 注意 这里的引入顺序会影响后面的样式叠加
import * as alertLess from './alert.less'
import * as avatarLess from './avatar.less'
import * as buttonLess from './button.less'
import * as backTopLess from './backTop.less'
import * as dropdownLess from './dropdown.less'
import * as hidableLess from './hidable.less'
import * as listLess from './list.less'
import * as messageLess from './message.less'
import * as tableLess from './table.less'
import * as scrollLess from './scroll.less'
import * as paginationLess from './pagination.less'
import * as breadcrumbLess from './breadcrumb.less'
import * as iconLess from './icon.less'
import * as menuLess from './menu.less'
import * as checkInputLess from './checkinput.less'
import * as formLess from './form.less'
import * as inputLess from './form.less'
import * as selectLess from './select.less'
import * as treeSelectLess from './treeSelect.less'
import * as modalLess from './modal.less'
import * as cardLess from './card.less'
import * as datepickerLess from './datepicker.less'
import * as rateLess from './rate.less'
import * as imageLess from './image.less'
import * as tooltipLess from './tooltip.less'
import * as popoverLess from './popover.less'
import * as treeLess from './tree.less'
import * as sliderLess from './slider.less'
import * as stepsLess from './steps.less'
import * as tabsLess from './tabs.less'
import * as tagLess from './tag.less'
import * as progressLess from './progress.less'
import * as uploadLess from './upload.less'
import * as carouselLess from './carousel.less'
import * as cascaderLess from './cascader.less'
import * as transferLess from './transfer.less'
import * as spinLess from './spin.less'
import * as cardGroupLess from './cardGroup.less'
import * as editableAreaLess from './editableArea.less'
import * as moveableLess from './moveable.less'
import * as resizableLess from './resizable.less'
import * as lazyloadLess from './lazyload.less'
import * as loadingLess from './loading.less'
import * as badgeLess from './badge.less'
import * as timeLineLess from './timeLine.less'
import * as photoViewLess from './photoView.less'
import * as swiperLess from './swiper.less'

export const alertClass = genaration(alertLess, 'alert')
export const avatarClass = genaration(avatarLess, 'avatar')
export const backTopClass = genaration(backTopLess, 'backTop')
export const buttonClass = genaration(buttonLess, 'button')
export const badgeClass = genaration(badgeLess, 'badge')
export const dropdownClass = genaration(dropdownLess, 'dropdown')
export const hidableClass = genaration(hidableLess, 'hidable')
export const listClass = genaration(listLess, 'list')
export const messageClass = genaration(messageLess, 'message')
export const tableClass = genaration(tableLess, 'table')
export const scrollClass = genaration(scrollLess, 'scroll')
export const paginationClass = genaration(paginationLess, 'pagination')
export const breadcrumbClass = genaration(breadcrumbLess, 'breadcrumb')
export const iconClass = genaration(iconLess, 'icon')
export const menuClass = genaration(menuLess, 'menu')
export const checkInputClass = genaration(checkInputLess, 'checkinput')
export const formClass = genaration(formLess, 'form')
export const inputClass = genaration(inputLess, 'input')
export const selectClass = genaration(selectLess, 'select')
export const treeSelectClass = genaration(treeSelectLess, 'treeSelect')
export const modalClass = genaration(modalLess, 'modal')
export const cardClass = genaration(cardLess, 'card')
export const datepickerClass = genaration(datepickerLess, 'datepicker')
export const rateClass = genaration(rateLess, 'rate')
export const imageClass = genaration(imageLess, 'image')
export const tooltipClass = genaration(tooltipLess, 'tooltip')
export const popoverClass = genaration(popoverLess, 'popover')
export const treeClass = genaration(treeLess, 'tree')
export const sliderClass = genaration(sliderLess, 'slider')
export const tabsClass = genaration(tabsLess, 'tabs')
export const tagClass = genaration(tagLess, 'tag')
export const progressClass = genaration(progressLess, 'progress')
export const uploadClass = genaration(uploadLess, 'upload')
export const carouselClass = genaration(carouselLess, 'carousel')
export const cascaderClass = genaration(cascaderLess, 'cascader')
export const transferClass = genaration(transferLess, 'transfer')
export const spinClass = genaration(spinLess, 'spin')
export const stepsClass = genaration(stepsLess, 'steps')
export const cardGroupClass = genaration(cardGroupLess, 'card-group')
export const editableAreaClass = genaration(editableAreaLess, 'editableArea')
export const moveableClass = genaration(moveableLess, 'moveable')
export const resizableClass = genaration(resizableLess, 'resizable')
export const lazyloadClass = genaration(lazyloadLess, 'lazyload')
export const loadingClass = genaration(loadingLess, 'loading')
export const timeLineClass = genaration(timeLineLess, 'timeline')
export const photoViewClass = genaration(photoViewLess, 'photoView')
export const swiperClass = genaration(swiperLess, 'swiper')
