import './styles/normalize.less'

export { setLocale } from './locale'

export { default as Alert } from './component/Alert'
export { default as Button } from './component/Button'
export { default as Dropdown } from './component/Dropdown'
export { default as Icon } from './component/Icon'
export { default as Spin } from './component/Spin'
export { default as Loading } from './component/Loading'
export { FontAwesome } from './component/Icon'
export { default as Menu } from './component/Menu'
export { default as Sticky } from './component/Sticky'
export { default as Carousel } from './component/Carousel'
export { default as Lazyload } from './component/LazyLoad'
