/** Created by scripts/src-index.ts.  */
/** Do not manually change. */
/** Please run build-index to build index.ts */

export { setLocale } from './locale'
export { default as config, setConfig } from './config'
export { style } from './utils/style'
export { FontAwesome } from './component/Icon'
export { default as Lazyload } from './component/LazyLoad'

export { default as Alert } from './component/Alert'
export { default as Avatar } from './component/Avatar'
export { default as BackTop } from './component/BackTop'
export { default as Badge } from './component/Badge'
export { default as Breadcrumb } from './component/Breadcrumb'
export { default as Button } from './component/Button'
export { default as Card } from './component/Card'
export { default as Carousel } from './component/Carousel'
export { default as Cascader } from './component/Cascader'
export { default as Checkbox } from './component/Checkbox'
export { default as ClampLines } from './component/ClampLines'
export { default as ColorPicker } from './component/ColorPicker'
export { default as DatePicker } from './component/DatePicker'
export { default as Dropdown } from './component/Dropdown'
export { default as EditableArea } from './component/EditableArea'
export { default as Form } from './component/Form'
export { default as Grid } from './component/Grid'
export { default as Icon } from './component/Icon'
export { default as Image } from './component/Image'
export { default as Input } from './component/Input'
export { default as LazyList } from './component/LazyList'
export { default as LazyLoad } from './component/LazyLoad'
export { default as Loading } from './component/Loading'
export { default as Menu } from './component/Menu'
export { default as Message } from './component/Message'
export { default as Modal } from './component/Modal'
export { default as More } from './component/More'
export { default as Motion } from './component/Motion'
export { default as Pagination } from './component/Pagination'
export { default as Popover } from './component/Popover'
export { default as Portal } from './component/Portal'
export { default as Progress } from './component/Progress'
export { default as ProImage } from './component/ProImage'
export { default as Radio } from './component/Radio'
export { default as Rate } from './component/Rate'
export { default as ResizeObserver } from './component/ResizeObserver'
export { default as Rule } from './component/Rule'
export { default as Scroll } from './component/Scroll'
export { default as Select } from './component/Select'
export { default as Slider } from './component/Slider'
export { default as Spin } from './component/Spin'
export { default as Steps } from './component/Steps'
export { default as Sticky } from './component/Sticky'
export { default as Swiper } from './component/Swiper'
export { default as Switch } from './component/Switch'
export { default as Tabs } from './component/Tabs'
export { default as Tag } from './component/Tag'
export { default as Textarea } from './component/Textarea'
export { default as TimeLine } from './component/TimeLine'
export { default as Tooltip } from './component/Tooltip'
export { default as Transfer } from './component/Transfer'
export { default as Tree } from './component/Tree'
export { default as Trigger } from './component/Trigger'
export { default as Upload } from './component/Upload'
