import { Component } from 'react'
import PropTypes from 'prop-types'
import { defaultProps, getProps } from '@/utils/proptypes'
import shallowEqual from '@/utils/shallowEqual'
import { getUidStr } from '@/utils/uid'
